---
title: "P33_Martin_Robert"
date: "4/2/2017"
output: slidy_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r outside_code, echo = FALSE}
library(leaflet)
library(tmap)
library(tmaptools)
library(RColorBrewer)
library(scales)
stateColClasses <- c(rep("character", 7), rep("integer", 7))
stateAbbrNbrs <- read.csv("P3 state abbr.csv", stringsAsFactors = FALSE,
                          colClasses = stateColClasses)
stateAbbrNbrs$officers100 <- stateAbbrNbrs$NbrOfOfficers / 100
stateAbbrNbrs$officerAssault100 <- round(stateAbbrNbrs$OfficersAssaulted /
                                         stateAbbrNbrs$officers100)
usshapefile <- "cb_2015_us_state_5m.shp"
# Read in the shapefile for US states:
usgeo <- read_shape(file=usshapefile)
usgeo <- usgeo[order(usgeo@data$STUSPS), ]
stateAbbrNbrs <- stateAbbrNbrs[order(stateAbbrNbrs$StateAbbr), ]
# There are extra "states" / FIPS codes in usgeo
identical(factor(stateAbbrNbrs$StateAbbr), usgeo@data$STUSPS)
usmap <- append_data(usgeo, stateAbbrNbrs,
                     key.shp = "STUSPS", key.data="StateAbbr")
midwestFIPS <- c("17", "18", "19", "20", "26", "27", "29", "31", "38", "39",
                 "46", "55")
northeastFIPS <- c("09", "23", "25", "33", "34", "36", "42", "44", "50")
southFIPS <- c("01", "05", "10", "11", "12", "13", "21", "22", "24", "28",
               "37", "40", "45", "47", "48", "51", "54")
westFIPS <- c("02", "04", "06", "08", "15", "16", "30", "32", "35", "41",
              "49", "53", "56")
palGreens <- colorNumeric(palette = c("#C7E9C0", "#A1D99B", "#74C476", "#41AB5D",
                                      "#238B45", "#005A32"),
                          domain = usmap@data$officerAssault100)
midwestmap <- usmap[usmap@data$STATEFP %in% midwestFIPS, ]
midwestpopup <- paste0("<b>State: ", midwestmap@data$NAME,
                       "</b><br />Assaults: ",
                       midwestmap@data$OfficersAssaulted,
                       "</b><br />Assaults Per 100 Officers: ",
                       midwestmap@data$officerAssault100)
northeastmap <- usmap[usmap@data$STATEFP %in% northeastFIPS, ]
northeastpopup <- paste0("<b>State: ", northeastmap@data$NAME,
                       "</b><br />Assaults: ",
                       northeastmap@data$OfficersAssaulted,
                       "</b><br />Assaults Per 100 Officers: ",
                       northeastmap@data$officerAssault100)
southmap <- usmap[usmap@data$STATEFP %in% southFIPS, ]
southpopup <- paste0("<b>State: ", southmap@data$NAME,
                       "</b><br />Assaults: ",
                       southmap@data$OfficersAssaulted,
                       "</b><br />Assaults Per 100 Officers: ",
                       southmap@data$officerAssault100)
westmap <- usmap[usmap@data$STATEFP %in% westFIPS, ]
westpopup <- paste0("<b>State: ", westmap@data$NAME,
                     "</b><br />Assaults: ",
                     westmap@data$OfficersAssaulted,
                     "</b><br />Assaults Per 100 Officers: ",
                     westmap@data$officerAssault100)

```

## Law Enforcement Officers Killed and Assaulted

Using reactive expressions it's possible to control when datasets are updated.

```{r my_attempt}
library(shiny)
library(shinythemes)
shinyApp(
  ui = 
#  headerPanel("Law Enforcement Officers Killed and Assaulted"),
  sidebarPanel(
      conditionalPanel(condition="input.tabselected==1",
                       p("The Law Enforcement Officers Killed and Assaulted (LEOKA)
                         data is compiled and published by the FBI on an annual basis. 
                         The data is collected through several methods
                         including individual police agencies (sheriff, city)
                         submitting reports to the FBI, local FBI offices
                         reporting data, as well as FBI collecting data on
                         law enforcement agents killed or assaulted while
                         outside U.S. jurisdiction. Assaults are tracked by
                         type of weapon - hands, feet, knives, guns, with
                         personal weapons (e.g. hands, feet) being the primary
                         method of assault. Statistics are compiled at the
                         state and regional levels, and are the focus of
                         this presentation.")),
      conditionalPanel(condition="input.tabselected==2",
                       h3("Midwestern states"),
                       p("Click inside a state to see assault statistics")),
      conditionalPanel(condition="input.tabselected==3",
                       h3("Northeastern states"),
                       p("Click inside a state to see assault statistics")),
      conditionalPanel(condition="input.tabselected==4",
                       h3("Southern states"),
                       p("Click inside a state to see assault statistics")),
      conditionalPanel(condition="input.tabselected==5",
                       h3("Western states"),
                       p("Click inside a state to see assault statistics"),
                       p(),
                       p(),
                       p("Zoom out to see Alaska and Hawaii")),
      conditionalPanel(condition="input.tabselected==6",
#                       plotOutput("conclusion"),
                       p("Through statistical analysis, the four regions'
                         average number of assaults per 100 officers have
                         been compared to one another."))
    ),

  mainPanel(
      tabsetPanel(
        tabPanel("About", value = 1, tags$iframe(src="https://www.dropbox.com/s/z5r45tbnuq8u2ky/P33%20Tab%201.pdf?raw=1",
                                                 width = "900", height = "600")),
        tabPanel("Midwest", value = 2, leafletOutput("midwest")),
        tabPanel("Northeast", value = 3, leafletOutput("northeast")),
        tabPanel("South", value = 4, leafletOutput("south")),
        tabPanel("West", value = 5, leafletOutput("west")),
        tabPanel("Conclusion", value = 6, tags$iframe(src="https://www.dropbox.com/s/z5r45tbnuq8u2ky/P33%20Tab%201.pdf?raw=1",
                                                      width = "900", height = "600")),
        id = "tabselected"
      )
    ),
  server = function(input, output){
    
          output$midwest <- renderLeaflet(leaflet(midwestmap) %>%
                                    addProviderTiles("CartoDB.Positron") %>%
                                    addPolygons(stroke=FALSE, 
                                                smoothFactor = 0.2, 
                                                fillOpacity = .3, 
                                                popup=midwestpopup, 
                                                color= ~palGreens(midwestmap@data$officerAssault100)
                                    ) %>% fitBounds(-102.5, 36.5, -79, 49.5)
                                      %>% addLegend("bottomright",
                                                    title = "Assaults per 100 Officers",
                                                    pal = palGreens,
                                                    values = ~usmap@data$officerAssault100,
                                                    opacity = 0.8
                                                    )
                                   )
      output$northeast <- renderLeaflet(leaflet(northeastmap) %>%
                                        addProviderTiles("CartoDB.Positron") %>%
                                        addPolygons(stroke=FALSE, 
                                                    smoothFactor = 0.2, 
                                                    fillOpacity = .3, 
                                                    popup=northeastpopup, 
                                                    color= ~palGreens(northeastmap@data$officerAssault100))
                                        %>% fitBounds(-81, 39, -67, 48)
#                                        %>% setView(-80, 39, zoom = 5)
                                      %>% addLegend("bottomright",
                                                    title = "Assaults per 100 Officers",
                                                    pal = palGreens,
                                                    values = ~usmap@data$officerAssault100,
                                                    opacity = 0.8
                                      )
      )
      output$south <- renderLeaflet(leaflet(southmap) %>%
                                          addProviderTiles("CartoDB.Positron") %>%
                                          addPolygons(stroke=FALSE, 
                                                      smoothFactor = 0.2, 
                                                      fillOpacity = .3, 
                                                      popup=southpopup, 
                                                      color= ~palGreens(southmap@data$officerAssault100))
                                        %>% fitBounds(-107, 24, -75, 40)
                                        %>% addLegend("bottomright",
                                                      title = "Assaults per 100 Officers",
                                                      pal = palGreens,
                                                      values = ~usmap@data$officerAssault100,
                                                      opacity = 0.8
                                        )
      )
      output$west <- renderLeaflet(leaflet(westmap) %>%
                                      addProviderTiles("CartoDB.Positron") %>%
                                      addPolygons(stroke=FALSE, 
                                                  smoothFactor = 0.2, 
                                                  fillOpacity = .3, 
                                                  popup=westpopup, 
                                                  color= ~palGreens(westmap@data$officerAssault100))
                                    %>% fitBounds(-125, 30, -102, 49)
                                    %>% addLegend("bottomright",
                                                  title = "Assaults per 100 Officers",
                                                  pal = palGreens,
                                                  values = ~usmap@data$officerAssault100,
                                                  opacity = 0.8
                                    )
      )
  }
)
```